INSERT INTO [dbo].[OrigineAliment] ([Nom]) VALUES ('américan')
INSERT INTO [dbo].[OrigineAliment] ([Nom]) VALUES ('belge')
INSERT INTO [dbo].[OrigineAliment] ([Nom]) VALUES ('anglais')
INSERT INTO [dbo].[OrigineAliment] ([Nom]) VALUES ('francais')
INSERT INTO [dbo].[OrigineAliment] ([Nom]) VALUES ('allemand')
INSERT INTO [dbo].[OrigineAliment] ([Nom]) VALUES ('greque')
INSERT INTO [dbo].[OrigineAliment] ([Nom]) VALUES ('italian')
INSERT INTO [dbo].[OrigineAliment] ([Nom]) VALUES ('mexicain')
INSERT INTO [dbo].[OrigineAliment] ([Nom]) VALUES ('suédois')
INSERT INTO [dbo].[OrigineAliment] ([Nom]) VALUES ('autre')

INSERT INTO [dbo].[TypeAliment] ([Nom]) VALUES ('Petit déjeuner')
INSERT INTO [dbo].[TypeAliment] ([Nom]) VALUES ('Déjeuner')
INSERT INTO [dbo].[TypeAliment] ([Nom]) VALUES ('Dîner')
INSERT INTO [dbo].[TypeAliment] ([Nom]) VALUES ('Plat d''accompagnement')
INSERT INTO [dbo].[TypeAliment] ([Nom]) VALUES ('Goûter')
INSERT INTO [dbo].[TypeAliment] ([Nom]) VALUES ('Dessert')
INSERT INTO [dbo].[TypeAliment] ([Nom]) VALUES ('Boisson')
INSERT INTO [dbo].[TypeAliment] ([Nom]) VALUES ('Autre')

INSERT INTO [dbo].[UniteDeMesure] (Nom, SystemeDeMesure) VALUES ('cuillère à café', 0)
INSERT INTO [dbo].[UniteDeMesure] (Nom, SystemeDeMesure) VALUES ('cuillère à soupe', 0)
INSERT INTO [dbo].[UniteDeMesure] (Nom, SystemeDeMesure) VALUES ('tasse', 0)
INSERT INTO [dbo].[UniteDeMesure] (Nom, SystemeDeMesure) VALUES ('pinte', 0)
INSERT INTO [dbo].[UniteDeMesure] (Nom, SystemeDeMesure) VALUES ('quart', 0)
INSERT INTO [dbo].[UniteDeMesure] (Nom, SystemeDeMesure) VALUES ('gallon', 0)
INSERT INTO [dbo].[UniteDeMesure] (Nom, SystemeDeMesure) VALUES ('once', 0)
INSERT INTO [dbo].[UniteDeMesure] (Nom, SystemeDeMesure) VALUES ('livre', 0)
INSERT INTO [dbo].[UniteDeMesure] (Nom, SystemeDeMesure) VALUES ('ml', 1)
INSERT INTO [dbo].[UniteDeMesure] (Nom, SystemeDeMesure) VALUES ('litre', 1)
INSERT INTO [dbo].[UniteDeMesure] (Nom, SystemeDeMesure) VALUES ('mg', 1)
INSERT INTO [dbo].[UniteDeMesure] (Nom, SystemeDeMesure) VALUES ('g', 1)
INSERT INTO [dbo].[UniteDeMesure] (Nom, SystemeDeMesure) VALUES ('kg', 1)

INSERT INTO [dbo].[Recette] (Nom,SystemeDeMesure,TemperatureDeCuisson,TempsDeCuisson,Instructions,TypeAlimentId,OrigineAlimentId) VALUES ('Salade de canneberges',0,NULL,NULL,'Mélanger les canneberges, le sucre, la cannelle, la muscade et le jus d''orange dans une casserole de taille moyenne. Cuire à feu moyen jusqu''à dissolution du sucre et ébullition des jus. Réduire le feu, couvrir et laisser mijoter, en remuant de temps en temps, jusqu''à ce que les canneberges éclatent et que le mélange prenne l''apparence d''une confiture. Ajouter les poires, l''ananas et le bourbon (ou tout autre liqueur) et bien mélanger. L’alcool s’évaporera, laissant derrière lui des saveurs plus fortes. Laisser refroidir au réfrigérateur. Servir froid.',6,1)
INSERT INTO [dbo].[Recette] (Nom,SystemeDeMesure,TemperatureDeCuisson,TempsDeCuisson,Instructions,TypeAlimentId,OrigineAlimentId) VALUES ('Bol à pain italien', 0, 400, 20, 'Dans un grand bol, dissoudre la levure dans de l''eau tiède. Laisser reposer jusqu''à onctuosité, environ 10 minutes. Ajouter le sel, l''huile et 480 g de farine au mélange de levure ; bien battre. Incorporer le reste de la farine progressivement en battant bien avec un mélangeur électrique à vitesse moyenne. Une fois que la pâte a pris forme, la retourner sur une surface légèrement farinée et la pétrir jusqu''à ce qu''elle soit lisse et élastique, environ 6 minutes. Huiler légèrement un grand bol, placer la pâte dans le bol et tourner plusieurs fois pour recouvrir complètement d''huile. Couvrir d''un chiffon humide et laisser lever la pâte dans un endroit chaud jusqu''à ce que le volume double, environ 40 minutes. Aplatir la pâte et la diviser en 8 parts égales. Former des petits pains ronds d''environ 10 cm de large. Déposer les pains sur des plaques de cuisson légèrement graissées et saupoudrer de farine. Couvrir et laisser lever dans un endroit chaud pendant Préchauffer le four à 200 degrés. Dans un petit bol, battre ensemble le blanc d''œuf et 1 cuillère à soupe d''eau ; brosser légèrement les pains avec la moitié de ce mélange. Cuire 15 minutes au four préchauffé. Badigeonner avec le reste du mélange d''œufs. Cuire 10 à 15 minutes de plus ou jusqu''à ce qu''il soit doré. Laisser refroidir sur les grilles. Pour faire les bols de pain : Couper une tranche d''1 cm d''épaisseur à partir du haut de chaque pain ; retirer la mie. Remplir les bols de pain avec la soupe chaude et servir immédiatement.', 4, 7)
INSERT INTO [dbo].[Recette] (Nom,SystemeDeMesure,TemperatureDeCuisson,TempsDeCuisson,Instructions,TypeAlimentId,OrigineAlimentId) VALUES ('Bœuf Stroganoff sans gluten', 0, NULL, NULL, 'TBD', 3, 10)
INSERT INTO [dbo].[Recette] (Nom,SystemeDeMesure,TemperatureDeCuisson,TempsDeCuisson,Instructions,TypeAlimentId,OrigineAlimentId) VALUES ('Scones allemands', 0, NULL, NULL, 'Dissoudre la levure dans de l''eau chaude. Ajouter 1 cuillère à soupe de sucre ; réserver. Verser l''eau bouillante sur le reste 60 g de sucre, le beurre et le sel. Ajouter les œufs, bien mélanger. Ajouter le mélange de levure et de farine. Battre au mixeur jusqu''à obtenir un mélange lisse. Ajouter les 150 g de sucre restants et mélanger. Laisser reposer pendant 1 heure puis réfrigérer jusqu''à froid. Rouler très fin (environ 0.5 cm) sur une surface farinée, et couper en carrés de 6 ou 7 cm. Faire revenir les scones dans de l''huile chaude, puis les retourner et les faire revenir jusqu''à ce que les deux côtés soient dorés et bien gonflés. Servir les scones avec du beurre et du miel, du beurre de miel à la cannelle, de la confiture, ou saupoudrés de sucre granulé.', 6, 5)
INSERT INTO [dbo].[Recette] (Nom,SystemeDeMesure,TemperatureDeCuisson,TempsDeCuisson,Instructions,TypeAlimentId,OrigineAlimentId) VALUES ('Quiche italienne aux légumes verts', 0, 375, 50, 'Préchauffer le four à 190°C. Préparer la pâte comme indiqué sur la boîte en utilisant un moule à tarte de 22 cm. Faire cuire environ 8 minutes ou jusqu''à ce qu''elle soit très légèrement doré. Pendant ce temps, dans un bol, battre les œufs, la crème légère, la ricotta, le sel et le poivre au fouet ou à la fourchette jusqu''à ce obtenir un mélange homogène. Ajouter les légumes. Alterner couche de roquette et de fromage dans la coquille cuite. Verser le mélange d''œufs sur les couches de roquette et de fromage. Cuire 40 à 50 minutes. Laisser refroidir 5 minutes avant de servir. Découper en quartier. A conserver au réfrigérateur.', 3, 7)
INSERT INTO [dbo].[Recette] (Nom,SystemeDeMesure,TemperatureDeCuisson,TempsDeCuisson,Instructions,TypeAlimentId,OrigineAlimentId) VALUES ('Gâteau à trois couches à la fraise',0,350,23,'1. Préparation - Préchauffer le four à 180°C. Recouvrir le fond de 3 casseroles de 20 cm de papier sulfurisé et vaporiser de spray de cuisson antiadhésif. Réserver. 2. Dans un grand bol, mélanger tous les ingrédients au mixeur électrique à basse température. Racler le côté du bol, augmenter la vitesse du batteur et battre pendant 3 minutes. 3. Verser la pâte à gâteau dans les casseroles préalablement préparées et cuire environ 23 minutes. 4. Laisser refroidir le gâteau sur une volette à pâtisserie pendant environ 10 minutes. Retirer des casseroles et laisser refroidir complètement. Si vous suivez la recette suivante pour la fabrication d''une crème au beurre à la fraise, réfrigérez les gâteaux jusqu''à ce qu''ils soient bien froids. 5. Pendant ce temps, préparez le glaçage. Dans un grand bol, battre le beurre à feu moyen jusqu’à ce qu''il soit jaune pâle et crèmeux. Ajouter le sucre en poudre et les fraises et battre à feu doux jusqu''à obtenir un mélange homogène. Placez-le au réfrigérateur pendant environ 5 à 10 minutes pour raffermir légèrement le mélange. 6. Étaler une couche de glaçage puis mettre en réfrigérateur. Ajouter la deuxième couche de glaçage et réfrigérer jusqu''à ce que les deux couches soient bien fermes. Assembler les couches et flacer le dessus et les côtés. Mettre au réfrigérateur.',6,1)
INSERT INTO [dbo].[Recette] (Nom,SystemeDeMesure,TemperatureDeCuisson,TempsDeCuisson,Instructions,TypeAlimentId,OrigineAlimentId) VALUES ('Soupe de tortilla',0,NULL,NULL,'Dans une grande marmite, faire dorer le porc puis ajouter l''oignon et l''ail et continuer la cuisson jusqu''à ce que les oignons soient dorés. Cette prochaine étape peut sembler pénible, mais elle ne prend que quelques minutes et en vaut la peine. Pendant que la cuisson du porc, retournez les tomates et faites un trou dans le fond de chaque tomate. Remplissez une petite casserole d''eau et portez-la à ébullition. Lorsque l''eau bout, remplir un bol de glace, puis compléter avec de l''eau. Déposer les tomates dans l''eau bouillante une à une pendant 20 secondes. Les retirer de l''eau bouillante à l''aide d''une cuillère à rainures et les plonger dans l''eau glacée. A l''aide d''un couteau d''office, retirer le centre et la peau de chaque tomate. Couper la tomate en deux, de haut en bas, et la presser afin de retirer le jus et les pépins. Couper les tomates en morceaux d''un centimètre de large environ. Ajouter les tomates, le bouillon de poulet, le piment poblano, le jalapeno, l''ail et les épices au porc et aux oignons. Porter à ébullition, puis réduire le feu et laisser mijoter pendant 45 minutes. Remplir les bols à soupe à moitié de bandes de tortilla, puis verser la soupe. Placer la garniture dans des petits bols. Chaque convive pourra garnir sa soupe selon ses préférences.',4,8)
INSERT INTO [dbo].[Recette] (Nom,SystemeDeMesure,TemperatureDeCuisson,TempsDeCuisson,Instructions,TypeAlimentId,OrigineAlimentId) VALUES ('Crêpes moelleuses au son d''avoine', 0, NULL, NULL, 'Mélanger les sucres et les jaunes d''œufs jusqu''à dissolution du sucre. Ajouter la vanille, le lait et le beurre et fouetter jusqu''à ce qu''ils soient bien mélangés. Dans un bol séparé, mélanger la farine, le son d''avoine, la levure chimique et le sel. Incorporer les liquides jusqu''à ce qu''à obtenir un mélange homogène. Dans un petit bol, battre les blancs d''œufs avec un mixeur électrique à vitesse moyenne jusqu''à ce que des pics raides apparaissent. Former la pâte. Graisser légèrement une plaque non chauffée ou une grande poêle antiadhésive. Préchauffer à feu moyen. Pour chaque crêpe, déposer une louchée de pâte dans une poêle ; si nécessaire, étaler afin de former un cercle de 10 cm environ. Faire cuire environ 2 minutes de chaque côté ou jusqu''à ce que les crêpes soient dorées.', 4, 10)
INSERT INTO [dbo].[Recette] (Nom,SystemeDeMesure,TemperatureDeCuisson,TempsDeCuisson,Instructions,TypeAlimentId,OrigineAlimentId) VALUES ('Soupe aux œufs', 0, NULL, NULL, 'Porter à ébullition le bouillon de soupe, le gingembre et la sauce soja. Dans un petit bol, mélanger la fécule de maïs et 2 cuillères à soupe d''eau. Mélanger jusqu''à dissolution de la fécule de maïs. Verser lentement le mélange de fécule de maïs dans le bouillon jusqu''à ce qu''il épaississe un peu. Réduire à petit feu. Verser lentement les œufs et mélanger dans un seul sens. La mixture s''étirera pour prendre la forme de rubans. Retirer la soupe du feu et ajouter les oignons verts. Assaisonner de sel et de poivre.', 4, 10)
INSERT INTO [dbo].[Recette] (Nom,SystemeDeMesure,TemperatureDeCuisson,TempsDeCuisson,Instructions,TypeAlimentId,OrigineAlimentId) VALUES ('Barres d''avoine au chocolat sans cuisson', 0, NULL, NULL, '1. Recouvrir d''un papier sulfurisé un plat allant au four de 20 x 20 cm, et réserver. 2. Dans une casserole de taille moyenne, faire chauffer le beurre, puis réduire le feu et ajouter la cassonade et l''extrait de vanille. Chauffer jusqu''à dissolution du sucre. 3. Ajouter l''avoine, la cannelle et le sel au mélange beurre/sucre et faire cuire en remuant constamment pendant 4 à 5 minutes. 4. Verser la moitié du mélange d''avoine dans le plat. Etalez le mélange uniformément, en appuyant dessus. 5. Dans un petit bol à micro-ondes, mélanger les morceaux de chocolat et le beurre d''arachide. Chauffer à haute température dans le four à micro-ondes, par intervalles de 40 secondes, en remuant régulièrement, jusqu''à obtenir un mélange homogène. 6. Réserver 6cl du mélange. Verser le reste dans la casserole sur l''avoine pressé. Garnir avec le reste d''avoine et arroser du reste de chocolat. 7. Réfrigérer pendant 4 heures, ou jusqu''à obtenir la texture désirée.', 6, 1)

INSERT INTO Ingredient (Quantite, UniteDeMesureId, Nom) VALUES (12, 7, 'canneberges fraîches')
INSERT INTO Ingredient (Quantite, UniteDeMesureId, Nom) VALUES (0.75, 3, 'sucre roux')
INSERT INTO Ingredient (Quantite, UniteDeMesureId, Nom) VALUES (0.25, 3, 'jus d''orange frais')
INSERT INTO Ingredient (Quantite, UniteDeMesureId, Nom) VALUES (0.25, 1, 'cannelle grillée')
INSERT INTO Ingredient (Quantite, UniteDeMesureId, Nom) VALUES (0.125, 1, 'muscade')
INSERT INTO Ingredient (Quantite, UniteDeMesureId, Nom) VALUES (1, 3, 'poires pelées et hachées')
INSERT INTO Ingredient (Quantite, UniteDeMesureId, Nom) VALUES (1, 3, 'ananas haché')
INSERT INTO Ingredient (Quantite, UniteDeMesureId, Nom) VALUES (0.25, 3, 'bourbon,  rhum épicé ou brandy')
INSERT INTO Ingredient (Quantite, UniteDeMesureId, Nom) VALUES (0.5, 7, 'levure sèche active')
INSERT INTO Ingredient (Quantite, UniteDeMesureId, Nom) VALUES (2.5, 3, 'eau chaude (110° F / 45° C)')
INSERT INTO Ingredient (Quantite, UniteDeMesureId, Nom) VALUES (2, 1, 'sel')
INSERT INTO Ingredient (Quantite, UniteDeMesureId, Nom) VALUES (2, 2, 'huile d''olive')
INSERT INTO Ingredient (Quantite, UniteDeMesureId, Nom) VALUES (7, 3, 'farine - tout usage')
INSERT INTO Ingredient (Quantite, UniteDeMesureId, Nom) VALUES (1, 2, 'farine de maïs')
INSERT INTO Ingredient (Quantite, UniteDeMesureId, Nom) VALUES (1, NULL, 'blanc d''œuf')
INSERT INTO Ingredient (Quantite, UniteDeMesureId, Nom) VALUES (1, 2, 'eau')
INSERT INTO Ingredient (Quantite, UniteDeMesureId, Nom) VALUES (1.5, 8, 'steak ou bœuf haché en fines tranches')
INSERT INTO Ingredient (Quantite, UniteDeMesureId, Nom) VALUES (2, 2, 'beurre fondu ou huile d''olive')
INSERT INTO Ingredient (Quantite, UniteDeMesureId, Nom) VALUES (1, NULL, 'petit oignon blanc - tranché ou coupé en dés')
INSERT INTO Ingredient (Quantite, UniteDeMesureId, Nom) VALUES (8, 7, 'champignons cremini finement tranchés')
INSERT INTO Ingredient (Quantite, UniteDeMesureId, Nom) VALUES (4, NULL, 'gousses d''ail hachées')
INSERT INTO Ingredient (Quantite, UniteDeMesureId, Nom) VALUES (2, 2, 'farine sans gluten')
INSERT INTO Ingredient (Quantite, UniteDeMesureId, Nom) VALUES (0.5, 3, 'vin blanc sec')
INSERT INTO Ingredient (Quantite, UniteDeMesureId, Nom) VALUES (1.5, 3, 'bouillon de bœuf')
INSERT INTO Ingredient (Quantite, UniteDeMesureId, Nom) VALUES (1, 2, 'Sauce Worcestershire')
INSERT INTO Ingredient (Quantite, UniteDeMesureId, Nom) VALUES (0.5, 3, 'crème de noix de coco')
INSERT INTO Ingredient (Quantite, UniteDeMesureId, Nom) VALUES (0.5, 7, 'levure active sèche')
INSERT INTO Ingredient (Quantite, UniteDeMesureId, Nom) VALUES (0.5, 3, 'eau')
INSERT INTO Ingredient (Quantite, UniteDeMesureId, Nom) VALUES (1, 2, 'sucre')
INSERT INTO Ingredient (Quantite, UniteDeMesureId, Nom) VALUES (0.5, 3, 'sucre')
INSERT INTO Ingredient (Quantite, UniteDeMesureId, Nom) VALUES (1, 3, 'eau bouillante')
INSERT INTO Ingredient (Quantite, UniteDeMesureId, Nom) VALUES (0.5, 3, 'beurre')
INSERT INTO Ingredient (Quantite, UniteDeMesureId, Nom) VALUES (2, 1, 'sel')
INSERT INTO Ingredient (Quantite, UniteDeMesureId, Nom) VALUES (3, NULL, 'œufs - battus')
INSERT INTO Ingredient (Quantite, UniteDeMesureId, Nom) VALUES (4.5, 3, 'farine - tout usage')
INSERT INTO Ingredient (Quantite, UniteDeMesureId, Nom) VALUES (1, NULL, 'pâte à tarte réfrigérée,  ramollie comme indiqué sur la boîte')
INSERT INTO Ingredient (Quantite, UniteDeMesureId, Nom) VALUES (5, NULL, 'œufs - battus')
INSERT INTO Ingredient (Quantite, UniteDeMesureId, Nom) VALUES (1, 3, 'crème 11, 5 % M.G.')
INSERT INTO Ingredient (Quantite, UniteDeMesureId, Nom) VALUES (1, 3, 'fromage ricotta')
INSERT INTO Ingredient (Quantite, UniteDeMesureId, Nom) VALUES (0.5, 3, 'Persil italien - finement haché')
INSERT INTO Ingredient (Quantite, UniteDeMesureId, Nom) VALUES (0.25, 3, 'oignon vert - haché')
INSERT INTO Ingredient (Quantite, UniteDeMesureId, Nom) VALUES (0.25, 3, 'chou frisé')
INSERT INTO Ingredient (Quantite, UniteDeMesureId, Nom) VALUES (2, 3, 'mozzarella - râpé')
INSERT INTO Ingredient (Quantite, UniteDeMesureId, Nom) VALUES (1, NULL, 'préparation pour gâteau')
INSERT INTO Ingredient (Quantite, UniteDeMesureId, Nom) VALUES (3, 7, 'gelée de fraise (boîte)')
INSERT INTO Ingredient (Quantite, UniteDeMesureId, Nom) VALUES (4, NULL, 'œufs')
INSERT INTO Ingredient (Quantite, UniteDeMesureId, Nom) VALUES (0.5, 3, 'sucre')
INSERT INTO Ingredient (Quantite, UniteDeMesureId, Nom) VALUES (0.25, 3, 'farine - tout usage')
INSERT INTO Ingredient (Quantite, UniteDeMesureId, Nom) VALUES (0.5, 3, 'fraises fraîches - finement tranchées')
INSERT INTO Ingredient (Quantite, UniteDeMesureId, Nom) VALUES (1, 3, 'huile végétale')
INSERT INTO Ingredient (Quantite, UniteDeMesureId, Nom) VALUES (0.5, 3, 'lait')
INSERT INTO Ingredient (Quantite, UniteDeMesureId, Nom) VALUES (2, 8, 'épaule de porc - en cubes')
INSERT INTO Ingredient (Quantite, UniteDeMesureId, Nom) VALUES (2, 2, 'huile de maïs')
INSERT INTO Ingredient (Quantite, UniteDeMesureId, Nom) VALUES (1, NULL, 'oignon blanc - haché fin')
INSERT INTO Ingredient (Quantite, UniteDeMesureId, Nom) VALUES (2, NULL, 'gousses d''ail hachées')
INSERT INTO Ingredient (Quantite, UniteDeMesureId, Nom) VALUES (12, NULL, 'tomates Roma - coupées en dés')
INSERT INTO Ingredient (Quantite, UniteDeMesureId, Nom) VALUES (6, 3, 'bouillon de poulet')
INSERT INTO Ingredient (Quantite, UniteDeMesureId, Nom) VALUES (1, NULL, 'piment poblano - rôti,  épluché,  haché')
INSERT INTO Ingredient (Quantite, UniteDeMesureId, Nom) VALUES (1, NULL, 'jalepeno - ensemencé et haché')
INSERT INTO Ingredient (Quantite, UniteDeMesureId, Nom) VALUES (0.5, 1, 'cumin')
INSERT INTO Ingredient (Quantite, UniteDeMesureId, Nom) VALUES (1, 1, 'poudre de piment')
INSERT INTO Ingredient (Quantite, UniteDeMesureId, Nom) VALUES (0.75, 1, 'poivre noir')
INSERT INTO Ingredient (Quantite, UniteDeMesureId, Nom) VALUES (10, NULL, 'tortillas de maïs - coupées en fines bandes')
INSERT INTO Ingredient (Quantite, UniteDeMesureId, Nom) VALUES (0.6666666666666666666666666667, 3, 'farine - tout usage')
INSERT INTO Ingredient (Quantite, UniteDeMesureId, Nom) VALUES (0.3333333333333333333333333333, 3, 'son d''avoine')
INSERT INTO Ingredient (Quantite, UniteDeMesureId, Nom) VALUES (1, 2, 'sucre roux')
INSERT INTO Ingredient (Quantite, UniteDeMesureId, Nom) VALUES (1, 1, 'vanille')
INSERT INTO Ingredient (Quantite, UniteDeMesureId, Nom) VALUES (0.125, 1, 'sel')
INSERT INTO Ingredient (Quantite, UniteDeMesureId, Nom) VALUES (1, 3, 'lait écrémé')
INSERT INTO Ingredient (Quantite, UniteDeMesureId, Nom) VALUES (1, 2, 'beurre fondu')
INSERT INTO Ingredient (Quantite, UniteDeMesureId, Nom) VALUES (2, NULL, 'œufs - séparés')
INSERT INTO Ingredient (Quantite, UniteDeMesureId, Nom) VALUES (4, 3, 'bouillon de poulet')
INSERT INTO Ingredient (Quantite, UniteDeMesureId, Nom) VALUES (0.5, 1, 'gingembre - râpé')
INSERT INTO Ingredient (Quantite, UniteDeMesureId, Nom) VALUES (2, 2, 'eau')
INSERT INTO Ingredient (Quantite, UniteDeMesureId, Nom) VALUES (1, 2, 'sauce soja')
INSERT INTO Ingredient (Quantite, UniteDeMesureId, Nom) VALUES (2, 2, 'fécule de maïs')
INSERT INTO Ingredient (Quantite, UniteDeMesureId, Nom) VALUES (2, NULL, 'œufs - battus')
INSERT INTO Ingredient (Quantite, UniteDeMesureId, Nom) VALUES (4, NULL, 'oignon vert - haché')
INSERT INTO Ingredient (Quantite, UniteDeMesureId, Nom) VALUES (1, 1, 'moutarde épicée')
INSERT INTO Ingredient (Quantite, UniteDeMesureId, Nom) VALUES (1, 3, 'beurre fondu')
INSERT INTO Ingredient (Quantite, UniteDeMesureId, Nom) VALUES (0.5, 3, 'sucre roux')
INSERT INTO Ingredient (Quantite, UniteDeMesureId, Nom) VALUES (1, 1, 'vanille')
INSERT INTO Ingredient (Quantite, UniteDeMesureId, Nom) VALUES (3, 3, 'flocons d''avoine')
INSERT INTO Ingredient (Quantite, UniteDeMesureId, Nom) VALUES (0.5, 1, 'cannelle')
INSERT INTO Ingredient (Quantite, UniteDeMesureId, Nom) VALUES (0.25, 1, 'sel')
INSERT INTO Ingredient (Quantite, UniteDeMesureId, Nom) VALUES (1, 3, 'morceaux de chocolat noir')
INSERT INTO Ingredient (Quantite, UniteDeMesureId, Nom) VALUES (0.75, 3, 'beurre d''arachide épais')

INSERT INTO [dbo].[IngredientRecette] ([RecetteId],[IngredientId]) VALUES (1,1)
INSERT INTO [dbo].[IngredientRecette] ([RecetteId],[IngredientId]) VALUES (1,2)
INSERT INTO [dbo].[IngredientRecette] ([RecetteId],[IngredientId]) VALUES (1,3)
INSERT INTO [dbo].[IngredientRecette] ([RecetteId],[IngredientId]) VALUES (1,4)
INSERT INTO [dbo].[IngredientRecette] ([RecetteId],[IngredientId]) VALUES (1,5)
INSERT INTO [dbo].[IngredientRecette] ([RecetteId],[IngredientId]) VALUES (1,6)
INSERT INTO [dbo].[IngredientRecette] ([RecetteId],[IngredientId]) VALUES (1,7)
INSERT INTO [dbo].[IngredientRecette] ([RecetteId],[IngredientId]) VALUES (1,8)
INSERT INTO [dbo].[IngredientRecette] ([RecetteId],[IngredientId]) VALUES (2,9)
INSERT INTO [dbo].[IngredientRecette] ([RecetteId],[IngredientId]) VALUES (2,10)
INSERT INTO [dbo].[IngredientRecette] ([RecetteId],[IngredientId]) VALUES (2,11)
INSERT INTO [dbo].[IngredientRecette] ([RecetteId],[IngredientId]) VALUES (2,12)
INSERT INTO [dbo].[IngredientRecette] ([RecetteId],[IngredientId]) VALUES (2,13)
INSERT INTO [dbo].[IngredientRecette] ([RecetteId],[IngredientId]) VALUES (2,14)
INSERT INTO [dbo].[IngredientRecette] ([RecetteId],[IngredientId]) VALUES (2,15)
INSERT INTO [dbo].[IngredientRecette] ([RecetteId],[IngredientId]) VALUES (2,16)
INSERT INTO [dbo].[IngredientRecette] ([RecetteId],[IngredientId]) VALUES (3,17)
INSERT INTO [dbo].[IngredientRecette] ([RecetteId],[IngredientId]) VALUES (3,18)
INSERT INTO [dbo].[IngredientRecette] ([RecetteId],[IngredientId]) VALUES (3,19)
INSERT INTO [dbo].[IngredientRecette] ([RecetteId],[IngredientId]) VALUES (3,20)
INSERT INTO [dbo].[IngredientRecette] ([RecetteId],[IngredientId]) VALUES (3,21)
INSERT INTO [dbo].[IngredientRecette] ([RecetteId],[IngredientId]) VALUES (3,22)
INSERT INTO [dbo].[IngredientRecette] ([RecetteId],[IngredientId]) VALUES (3,23)
INSERT INTO [dbo].[IngredientRecette] ([RecetteId],[IngredientId]) VALUES (3,24)
INSERT INTO [dbo].[IngredientRecette] ([RecetteId],[IngredientId]) VALUES (3,25)
INSERT INTO [dbo].[IngredientRecette] ([RecetteId],[IngredientId]) VALUES (3,26)
INSERT INTO [dbo].[IngredientRecette] ([RecetteId],[IngredientId]) VALUES (4,27)
INSERT INTO [dbo].[IngredientRecette] ([RecetteId],[IngredientId]) VALUES (4,28)
INSERT INTO [dbo].[IngredientRecette] ([RecetteId],[IngredientId]) VALUES (4,29)
INSERT INTO [dbo].[IngredientRecette] ([RecetteId],[IngredientId]) VALUES (4,30)
INSERT INTO [dbo].[IngredientRecette] ([RecetteId],[IngredientId]) VALUES (4,31)
INSERT INTO [dbo].[IngredientRecette] ([RecetteId],[IngredientId]) VALUES (4,32)
INSERT INTO [dbo].[IngredientRecette] ([RecetteId],[IngredientId]) VALUES (4,33)
INSERT INTO [dbo].[IngredientRecette] ([RecetteId],[IngredientId]) VALUES (4,34)
INSERT INTO [dbo].[IngredientRecette] ([RecetteId],[IngredientId]) VALUES (4,35)
INSERT INTO [dbo].[IngredientRecette] ([RecetteId],[IngredientId]) VALUES (5,36)
INSERT INTO [dbo].[IngredientRecette] ([RecetteId],[IngredientId]) VALUES (5,37)
INSERT INTO [dbo].[IngredientRecette] ([RecetteId],[IngredientId]) VALUES (5,38)
INSERT INTO [dbo].[IngredientRecette] ([RecetteId],[IngredientId]) VALUES (5,39)
INSERT INTO [dbo].[IngredientRecette] ([RecetteId],[IngredientId]) VALUES (5,40)
INSERT INTO [dbo].[IngredientRecette] ([RecetteId],[IngredientId]) VALUES (5,41)
INSERT INTO [dbo].[IngredientRecette] ([RecetteId],[IngredientId]) VALUES (5,42)
INSERT INTO [dbo].[IngredientRecette] ([RecetteId],[IngredientId]) VALUES (5,43)
INSERT INTO [dbo].[IngredientRecette] ([RecetteId],[IngredientId]) VALUES (6,44)
INSERT INTO [dbo].[IngredientRecette] ([RecetteId],[IngredientId]) VALUES (6,45)
INSERT INTO [dbo].[IngredientRecette] ([RecetteId],[IngredientId]) VALUES (6,46)
INSERT INTO [dbo].[IngredientRecette] ([RecetteId],[IngredientId]) VALUES (6,47)
INSERT INTO [dbo].[IngredientRecette] ([RecetteId],[IngredientId]) VALUES (6,48)
INSERT INTO [dbo].[IngredientRecette] ([RecetteId],[IngredientId]) VALUES (6,49)
INSERT INTO [dbo].[IngredientRecette] ([RecetteId],[IngredientId]) VALUES (6,50)
INSERT INTO [dbo].[IngredientRecette] ([RecetteId],[IngredientId]) VALUES (6,51)
INSERT INTO [dbo].[IngredientRecette] ([RecetteId],[IngredientId]) VALUES (7,52)
INSERT INTO [dbo].[IngredientRecette] ([RecetteId],[IngredientId]) VALUES (7,53)
INSERT INTO [dbo].[IngredientRecette] ([RecetteId],[IngredientId]) VALUES (7,54)
INSERT INTO [dbo].[IngredientRecette] ([RecetteId],[IngredientId]) VALUES (7,55)
INSERT INTO [dbo].[IngredientRecette] ([RecetteId],[IngredientId]) VALUES (7,56)
INSERT INTO [dbo].[IngredientRecette] ([RecetteId],[IngredientId]) VALUES (7,57)
INSERT INTO [dbo].[IngredientRecette] ([RecetteId],[IngredientId]) VALUES (7,58)
INSERT INTO [dbo].[IngredientRecette] ([RecetteId],[IngredientId]) VALUES (7,59)
INSERT INTO [dbo].[IngredientRecette] ([RecetteId],[IngredientId]) VALUES (7,60)
INSERT INTO [dbo].[IngredientRecette] ([RecetteId],[IngredientId]) VALUES (7,61)
INSERT INTO [dbo].[IngredientRecette] ([RecetteId],[IngredientId]) VALUES (7,62)
INSERT INTO [dbo].[IngredientRecette] ([RecetteId],[IngredientId]) VALUES (7,63)
INSERT INTO [dbo].[IngredientRecette] ([RecetteId],[IngredientId]) VALUES (8,64)
INSERT INTO [dbo].[IngredientRecette] ([RecetteId],[IngredientId]) VALUES (8,65)
INSERT INTO [dbo].[IngredientRecette] ([RecetteId],[IngredientId]) VALUES (8,66)
INSERT INTO [dbo].[IngredientRecette] ([RecetteId],[IngredientId]) VALUES (8,67)
INSERT INTO [dbo].[IngredientRecette] ([RecetteId],[IngredientId]) VALUES (8,68)
INSERT INTO [dbo].[IngredientRecette] ([RecetteId],[IngredientId]) VALUES (8,69)
INSERT INTO [dbo].[IngredientRecette] ([RecetteId],[IngredientId]) VALUES (8,70)
INSERT INTO [dbo].[IngredientRecette] ([RecetteId],[IngredientId]) VALUES (8,71)
INSERT INTO [dbo].[IngredientRecette] ([RecetteId],[IngredientId]) VALUES (9,72)
INSERT INTO [dbo].[IngredientRecette] ([RecetteId],[IngredientId]) VALUES (9,73)
INSERT INTO [dbo].[IngredientRecette] ([RecetteId],[IngredientId]) VALUES (9,74)
INSERT INTO [dbo].[IngredientRecette] ([RecetteId],[IngredientId]) VALUES (9,75)
INSERT INTO [dbo].[IngredientRecette] ([RecetteId],[IngredientId]) VALUES (9,76)
INSERT INTO [dbo].[IngredientRecette] ([RecetteId],[IngredientId]) VALUES (9,77)
INSERT INTO [dbo].[IngredientRecette] ([RecetteId],[IngredientId]) VALUES (9,78)
INSERT INTO [dbo].[IngredientRecette] ([RecetteId],[IngredientId]) VALUES (9,79)
INSERT INTO [dbo].[IngredientRecette] ([RecetteId],[IngredientId]) VALUES (10,80)
INSERT INTO [dbo].[IngredientRecette] ([RecetteId],[IngredientId]) VALUES (10,81)
INSERT INTO [dbo].[IngredientRecette] ([RecetteId],[IngredientId]) VALUES (10,82)
INSERT INTO [dbo].[IngredientRecette] ([RecetteId],[IngredientId]) VALUES (10,83)
INSERT INTO [dbo].[IngredientRecette] ([RecetteId],[IngredientId]) VALUES (10,84)
INSERT INTO [dbo].[IngredientRecette] ([RecetteId],[IngredientId]) VALUES (10,85)
INSERT INTO [dbo].[IngredientRecette] ([RecetteId],[IngredientId]) VALUES (10,86)
INSERT INTO [dbo].[IngredientRecette] ([RecetteId],[IngredientId]) VALUES (10,87)